### ISSUE TITLE
Testing APCAonly.98e_d12e.js results do not match

### ISSUE THREAD

**Issue by NateBaldwinDesign** [Myndex/SAPC-APCA#14]
Hi @Myndex, 

I'm testing a local implementation of APCA using `APCAonly.98e_d12e.js`. I have a test suite with the four test cases you have illustrated here: https://github.com/Myndex/SAPC-APCA/tree/master/JS#testing-your-implementation

However, my results do not match the expected results you've posted. I have tried transposing colors (assuming perhaps I had erroneously placed the text/background colors in the incorrect order). I am wondering if the test cases are incorrect, or if there's something I am missing?

Example of test case running locally:
```js
test('should provide APCA contrast for first test case', function() {
  let contrastValue = APCAcontrast(0xfff, 0x888);

  expect(contrastValue).toBe(66.89346308821438);
});
```

Result of test:
```
 Expected: 66.89346308821438
 Received: 11.399627561736908
```

**Comment by NateBaldwinDesign** [comment]
Figured this out -- the test needs to be run with full hexidecimal values: 
```
0xffffff
```
rather than 
```
0xfff
```

**Comment by Myndex** [comment]
Egads, really? I thought I had a routine that parsed 3 character colors correctly...  lemme take a look!!!

OH WAIT.... you can sent it ` fff ` as opposed to ` 0xfff ` and it should parse the string correctly (and expand to ffffff) , as opposed to sending the hex value which looks like ` 000fff ` ... 

ALSO, I discuss the most latest constants in the following issue thread here:

https://github.com/Myndex/SAPC-APCA/issues/12

**Comment by Myndex** [comment]
Just looked again, the current APCAonly does not have the input value parsing module that handles that that kind of thing, as the APCAonly JS is the most stripped down, without a number of other color related functions.

Thank you for bringing this to my attention... Now that some other code has stabilized I should bring it over to GitHub.

For reference, the file https://www.myndex.com/APCA/JS/DEV98G_SAPCsRGB.js includes color value input parsing and other features, as well as the latest code and constants.

Thank you!

Andy
