### ISSUE TITLE
NPM module

### ISSUE THREAD

**Issue by felixgirault** [Myndex/SAPC-APCA#34]
Hi,
Do you have any plans to release this code as a commonjs or es6 module ?
For now, it is impossible to use `APCAcontrast()` inside nodejs or using a web bundler.
I'd be glad to help if there is a need!

Thank you for your work anyways :)

**Comment by Myndex** [comment]
> Hi, Do you have any plans to release this code as a commonjs or es6 module ? For now, it is impossible to use `APCAcontrast()` inside nodejs or using a web bundler. I'd be glad to help if there is a need!

Yes, the exports were accidentally commented out, will have these issues fixed tonight (I hope) sorry for the issueS!!

And happy to accept comments or advice because...

![5xcebp](https://user-images.githubusercontent.com/42009457/145656850-b1760381-ee2b-4512-b5d7-5ebfdfd40971.jpg)

LOL

Thank you

Andy

**Comment by felixgirault** [comment]
😄 
No problem, there is no rush!
I could propose some changes to make the module more usable, but it may be a pain for you to manage if you're not fond of the JS ecosystem 🤔

**Comment by Myndex** [comment]
> 😄
> No problem, there is no rush!
> I could propose some changes to make the module more usable, but it may be a pain for you to manage if you're not fond of the JS ecosystem 🤔

I welcome the suggestions, as JS is "Lang du Jour" ... I just published the latest  which should fix the module export issue...

**Comment by felixgirault** [comment]
I just found out about the dedicated w3 repository!
I was going to propose something in the vein of this pull request https://github.com/Myndex/apca-w3/pull/1
I'm closing this issue as the discussion could continue there.
