### ISSUE TITLE
Foreground-foreground contrast

### ISSUE THREAD

**Issue by TaigaYamada** [Myndex/SAPC-APCA#38]
Hello.

I'm very much excited by the APCA contrast, and am looking to start using it.

Now the contrast calculation is situation-aware. That is, it differentiates between the text color and the background color.

However, how should one calculate the contrast between foreground objects? I'm currently looking to make accessible data visualization. So, I want to check if differently colored slices in pie chart can be recognized, for example.

Thank you in advance.

**Comment by Myndex** [comment]
Hi @TaigaYamada  thank you for writing,

The multi-way color tool is not out yet, and that would be best for pie charts.

In the interim, 

- If you have a small element against the larger background, the small element's color goes in the TEXT input.

- If you have a large element against the background or just some other large area of color, the, the DARKEST color goes in the TEXT input.
    - This is an interim but effective workaround.
    - The reason is that large color areas are interpreted differently, and polarity is not offset the same way if both the tested color areas are large and adjacent.

Please let me know if you have further questions!

Andy

**Comment by TaigaYamada** [comment]
Thank you for the reply.

I didn't know that there was a multi-way comparison tool in the works!

Meanwhile, I'll start with the workarounds you mentioned.

I'm looking forward to the future developments.

**Comment by Myndex** [comment]
Hi @TaigaYamada 
Cool! I'm going to close this issue, but please feel free to ask further questions!

**Comment by PeterNjeim** [comment]
@Myndex Hello, sorry to be a nag, but is this multi-way color tool in the backlog or is it abandoned? Any information is appreciated, will use the interim workaround you suggested above in the meantime, thanks

**Comment by Myndex** [comment]
> @Myndex Hello, sorry to be a nag, but is this multi-way color tool in the backlog or is it abandoned? Any information is appreciated, will use the interim workaround you suggested above in the meantime, thanks

Hi Peter @PeterNjeim 

It is in the development queue, as are many new features. Several are scheduled to be released, at least as public beta, this year (2024).
