### ISSUE TITLE
Where to apply the soft clamp

### ISSUE THREAD

**Issue by TaigaYamada** [Myndex/SAPC-APCA#47]
I am attempting to write a custom implementation of APCA contrast calculation.

I was reading the plain English steps in the README.md, and came across the following description for the step of soft-clamping the color.

- > Soft-clamp the colors but only if it is less than 0.022 Y

  "colors"(plural) implies that this operation should be done on both colors being compared

- > Then add that result back to the Y of the darker color 

  Here, the direction sounds like the clamping is only supposed to be done for darker of the 2 colors.

Should the soft-clamping be performed on both colors, or just the darker of the 2?

Thank you in advance.

**Comment by Myndex** [comment]
Hello @TaigaYamada 

Yes, to both colors. It is unlikely that you'll have both so low, and the result would likely be zero in that case. But it was changed to all input colors in anticipation of additional features for some versions.

You'll see in the actual code that both are processed.

Thank you!

Andy
