### ISSUE TITLE
Can't set "00" for green or blue values

### ISSUE THREAD

**Issue by mfishma** [Myndex/SAPC-APCA#5]
If I enter 980000 in either field, the resulting color is wrong.
Generating a unique URL shows me that it's actually showing 989898 color.

It seems that the R value is duplicated when G and B are 0

**Comment by Myndex** [comment]
> If I enter 980000 in either field, the resulting color is wrong.
> Generating a unique URL shows me that it's actually showing 989898 color.
> 
> It seems that the R value is duplicated when G and B are 0

Hi Mitch @mfishma 

### AH NUTS!

I thought I was being clever so entering "F3" only would give "F3F3F3"  but it should not have applied to F30000.

OOOps my bad. 

# 😳

# FIXED

Thank you VERY much for bringing this to my attention !!!!

Andy
