### ISSUE TITLE
AGPU license?

### ISSUE THREAD

**Issue by jtrim-ons** [Myndex/SAPC-APCA#63]
Thanks for this really useful project.

I noticed in the [source](https://github.com/Myndex/SAPC-APCA/blob/master/src/JS/SAPC_0_98G_4g_minimal.js) that the license is `AGPU v3`. Am I right in thinking that this should be `AGPL v3`?

**Comment by Myndex** [comment]
LOL.... doh! ... typo...  thank you, will 

Yea, AGPL, with modifications and exceptions during the beta period. The main one being revolkable, so that I cen get obsolete beta versions removed.

Thank you, will fix shortly..

**Comment by Secret-chest** [comment]
> LOL.... doh! ... typo... thank you, will
> 
> Yea, a modified AGPL, non commercial only, with modifications and exceptions during the beta period. The main one being revolkable, so that I cen get obsolete beta versions removed.
> 
> Thank you, will fix shortly..
> 
> EDIT to add: I had to make it "limited use, beta revokable" as there have been way too many incorrect and invalid instantiations out there, and too many early versions that are now obsolete. Because this relates to what will become a standard, we can't have these invalid versions out in the wild.

Once it is finished, will it be released under a free licence? I'm looking to develop a Python library implementing APCA, but I'll wait as I would like to be safe.

**Comment by Myndex** [comment]
> _Once it is finished, will it be released under a free licence? I'm looking to develop a Python library implementing APCA, but I'll wait as I would like to be safe_.

Yes, there will be a free limited license, and I expect to be grandfathering  some early adopters.

For now, for libraries, please include the disclaimer as listed, and see the conformance notes.

The eventual license will be permissive, just that there have been some issues  that make me question the wisdom of open development and an public beta program… LOL … it will all be sorted soon

**Comment by Secret-chest** [comment]
> Once it is finished, will it be released under a free licence? I'm looking to develop a Python library implementing APCA, but I'll wait as I would like to be safe.
> 
> Yes, there will be a free limited license, and I expect to be grandfathering some early adopters.
> 
> For now, for libraries, please include the disclaimer as listed, and see the conformance notes.
> 
> The eventual license will be permissive, just that there have been some issues that make me question the wisdom of open development and an public beta program… LOL … it will all be sorted soon

So fast... Alright, I'll wait for a permissive licence (the python library is not specifically for websites). Also, many thanks for the algorithm itself. Very useful!
