### ISSUE TITLE
Improve code structure 

### ISSUE THREAD

**Issue by lil5** [Myndex/SAPC-APCA#70]
Using typescript can help understand at a glance what the function will require and output. 

The function that calculates the minimum px per weight instantly concatenates with html, please separate.
If I understand correctly it would be 

```ts
minPixel(lc: number, weight: nummer): number
minPixelToHtml(minPx: number): string
```

**Comment by lil5** [comment]
here is an example of `minPixel` in typescript


```ts
const APCA_SORTED_BY_CONTRAST_LC100 = [46.5, 28.0, 18.0, 14.0, 14.0, 14.0, 14.0, 16.0, 18.0];
const APCA_SORTED_BY_CONTRAST_LC95 = [48.5, 29.0, 20.5, 14.5, 14.0, 14.0, 14.0, 16.0, 18.0];
const APCA_SORTED_BY_CONTRAST_LC90 = [50.0, 30.0, 21.0, 15.0, 14.5, 14.0, 14.0, 16.0, 18.0];
const APCA_SORTED_BY_CONTRAST_LC85 = [53.5, 32.0, 22.0, 16.0, 15.0, 14.0, 14.0, 16.0, 18.0];
const APCA_SORTED_BY_CONTRAST_LC80 = [56.5, 34.0, 23.0, 17.0, 16.0, 14.5, 14.0, 16.0, 18.0];
const APCA_SORTED_BY_CONTRAST_LC75 = [60.0, 36.0, 24.0, 18.0, 17.0, 15.0, 14.0, 16.0, 18.0];
const APCA_SORTED_BY_CONTRAST_LC70 = [65.0, 39.0, 27.5, 19.5, 18.0, 16.0, 14.5, 16.0, 18.0];
const APCA_SORTED_BY_CONTRAST_LC65 = [71.5, 43.0, 30.5, 21.5, 19.5, 17.0, 15.0, 16.0, 18.0];
const APCA_SORTED_BY_CONTRAST_LC60 = [80.0, 48.0, 34.0, 24.0, 21.0, 18.0, 16.0, 16.0, 18.0];
const APCA_SORTED_BY_CONTRAST_LC55 = [86.5, 52.0, 37.0, 26.0, 20.5, 18.5, 16.5, 16.0, 18.0];
const APCA_SORTED_BY_CONTRAST_LC50 = [92.5, 58.0, 41.0, 29.0, 22.0, 20.0, 17.5, 16.5, 18.0];
const APCA_SORTED_BY_CONTRAST_LC45 = [120.0, 72.0, 51.0, 36.0, 27.0, 23.5, 20.0, 18.0, 18.0];
const APCA_SORTED_BY_CONTRAST_LC40 = [160.0, 96.0, 68.0, 48.0, 34.0, 29.0, 24.0, 19.0, 18.0];
const APCA_SORTED_BY_CONTRAST_LC35 = [220.0, 132.0, 93.5, 66.0, 46.5, 40.0, 33.0, 26.5, 20.0];
const APCA_SORTED_BY_CONTRAST_LC30 = [320.0, 192.0, 135.0, 96.0, 68.0, 58.0, 48.0, 38.5, 29.0];

function ApcaLcToPixels(lc: number, weight: number): number | undefined {
  let lc_rounded = Math.round(lc);
  let index_weight: number = (() => {
    switch (weight) {
      case 100: return 0
      case 200: return 1
      case 300: return 2
      case 400: return 3
      case 500: return 4
      case 600: return 5
      case 700: return 6
      case 800: return 7
      case 900: return 8
      default: return undefined
    }
  })();

  switch (lc_rounded) {
    case 100: return APCA_SORTED_BY_CONTRAST_LC100[index_weight]
    case 95: return APCA_SORTED_BY_CONTRAST_LC95[index_weight]
    case 90: return APCA_SORTED_BY_CONTRAST_LC90[index_weight]
    case 85: return APCA_SORTED_BY_CONTRAST_LC85[index_weight]
    case 80: return APCA_SORTED_BY_CONTRAST_LC80[index_weight]
    case 75: return APCA_SORTED_BY_CONTRAST_LC75[index_weight]
    case 70: return APCA_SORTED_BY_CONTRAST_LC70[index_weight]
    case 65: return APCA_SORTED_BY_CONTRAST_LC65[index_weight]
    case 60: return APCA_SORTED_BY_CONTRAST_LC60[index_weight]
    case 55: return APCA_SORTED_BY_CONTRAST_LC55[index_weight]
    case 50: return APCA_SORTED_BY_CONTRAST_LC50[index_weight]
    case 45: return APCA_SORTED_BY_CONTRAST_LC45[index_weight]
    case 40: return APCA_SORTED_BY_CONTRAST_LC40[index_weight]
    case 35: return APCA_SORTED_BY_CONTRAST_LC35[index_weight]
    case 30: return APCA_SORTED_BY_CONTRAST_LC30[index_weight]
    default: return undefined
  }
}
```

**Comment by Myndex** [comment]
Hello Lucian  @lil5 

Sorry for the delay in reply, I didn't get a notification for some reason.

The "released" function on npm (the W3 version of APCA) does not concatenate with html, it returns an array of font sizes.

```js
   npm i apca-w3
```
and the GitHub repo for that version is https://github.com/Myndex/apca-w3 though issues and discussion are best over here.

In that version, fontLookupAPCA() returns an array where [0] is the Lc value, then elements [1] to [9] are the font sizes for weights 100-900. So as an example:

```js
    fontLookupAPCA(45.687);
```
returns:

```js
    [45.687,117,71,50,36,28,23.5,20,18,18]
```
i.e. the Lc value is 45.687, and a 400 weight font is 36px

And yes, I need to climb the typescript learning curve.

Does this answer your question? Or would you prefer that a function returned only a single font size as in:

```js
    fontLookupAPCA(45.687, 400);
```
would return ` 36 `

Side question: I'm considering adding interpolation for variable weights, so 

```js
    fontLookupAPCA(45.687, 350);
```
would return ` 43 `

Thank you for your comments!

Andy

**Comment by lil5** [comment]
> and the GitHub repo for that version is https://github.com/Myndex/apca-w3 though issues and discussion are best over here.

@Myndex I didn't know if I could trust that code as you aren't using that project yourself for the webapp.
Using es6 imports to have one point of truth concerning the Lc calculator will remove old code usage.

**Comment by Myndex** [comment]
> _I didn't know if I could trust that code as you aren't using that project yourself for the webapp. Using es6 imports to have one point of truth concerning the Lc calculator will remove old code usage._

Hi @lil5 — that is a by-product of active research. As things are now stabilizing, I have planned on using the APCA-W3 version for the main myndex.com/APCA/ website. The reason I hadn't was the need to respond promptly to testing/changing and issues early on mean making changes on the fly.

BUT ALSO: the APCA-W3 is intended to the Node.js ecosystem, and the website has features not in ACPA-W3 (like cleaning up keystroke entry, creating a URL with a given color pair, and the live text displays).  So to use the ` apca-w3.js` file means reworking more of that site than I have time, so I will when I can, but I have some other pressing priorities at the moment.

Also, I've had a plan to replace the current lookups with an algorithmic approach—that kind of thing will me on hte site well before it gets published in the npm package.


Thank you !!

**Comment by lil5** [comment]
> Also, I've had a plan to replace the current lookups with an algorithmic approach—that kind of thing will me on hte site well before it gets published in the npm package.

Looking forward to seeing that!

**Comment by Myndex** [comment]
Hello Lucian @lil5 

Just FYI, the tool site at myndex.com/APCA/ is now using a version of the apca-w3 package, so I'm going to close this PR for now, but please feel free to reopen or create a new one if you have more thoughts.

Thank you for reading

**Comment by sondr3** [comment]
Not to revive closed issues, but I wrote my own tool for WCAG/APCA contrast checking mostly as a learning exercise. I had a really hard time understanding the code for the font calculations but managed to figure it out, and implemented the APCA algorithm from the LaTeX document (so it can definitely be cleaner).

I've seen that you've been looking into improving the code structure/readability and adding tests, so you can take a look if you want for examples of APCA/WCAG in TypeScript: https://github.com/sondr3/a11y-color-contrast.

**Comment by Myndex** [comment]
> Not to revive closed issues, but I wrote my own tool for WCAG/APCA contrast checking mostly as a learning exercise. I had a really hard time understanding the code for the font calculations but managed to figure it out, and implemented the APCA algorithm from the LaTeX document (so it can definitely be cleaner).


Hi @sondr3 

I just now saw this message, I'm assuming that because this issue was closed that I wasn't actually notified. The code used in this repo for font assessment is not intended for code integration and not easy to parse I agree.

The code that you actually want to be using is at the APCA-W3 repo, or in the npm package.

https://github.com/Myndex/apca-w3/
