### ISSUE TITLE
Display-p3 and Adobe RGB constants are missing

### ISSUE THREAD

**Issue by svgeesus** [Myndex/SAPC-APCA#73]
**Does this relate to a web app or tool (i.e. you're an end user) OR is this about code or code integration (you're a developer).**

Neither.

**Describe the bug**

The readme section [Current APCA Constants ( 0.0.98G - W3 last changed Feb 15, 2021 )](https://github.com/Myndex/apca-w3#current-apca-constants--0098g---w3-last-changed-feb-15-2021-) lists linear sRGB to CIE Y constants for sRGB, only. The readme states that Display-P3 and Abobe RGB are also supported (which is good, given the current move towards display-p3 in CSS and Canvas) but these constants are not listed, nor is the transfer function given. Please put these values in the documentation.

Specifications and sample code are not the same thing.

**To Reproduce**
Steps so we can reproduce the behavior: read the readme

**Expected behavior**
What were you expecting as correct behavior? Values in the documentation

**Screenshots**
Add screenshots or code snippets to help explain your problem. **n/a**

**System or device information (please complete the following):**
- Device: [e.g. iPhone6 or iMac]
- OS: [e.g. MacOS]
- OS version
- **n/a**

**Comment by Myndex** [comment]
Hi Chris @svgeesus 

Just commenting to close this, the apca-w3 readme is updated with those constants (done last week, just now going though issues to close).

https://github.com/Myndex/apca-w3#current-apca-constants--0098g---w3-last-changed-feb-15-2021-

And also other related cleanup and documentation fixes. I'll close this PR, but please open an new one or reopen and lemme know if anything else is out of whack.
