### ISSUE TITLE
Proposal to drop "simple key levels"

### ISSUE THREAD

**Issue by xi** [Myndex/SAPC-APCA#89]
This is about the following section:

> - For simplicity, you can also use the “simple key levels” method (Lc 45, 60, 75), which compares to WCAG 2 contrast (with one very light color) as:
>
>    - Lc 45 is “sort of” like 3:1
>    - Lc 60 is “sort of” like 4.5:1
 >   - Lc 75 is “sort of” like 7:1

The web tool makes no mention of these "simple key level". Instead it defines the levels "bronze" (use cases that consider spatial frequency) and "silver" (look up table based on spatial frequency). The "simple key levels" on the other hand do not consider spatial frequency at all.

These "simple key levels" are attractive for people coming from WCAG 2 because you don't have to learn a lot of new concepts. I certainly fell into that trap. But if I understand correctly, these levels are not actually recommended.

So I believe the "simple key levels" do more harm than good. I therefore propose to remove them from the documentation.

**Comment by Myndex** [comment]
Hello @xi 

> _This is about the following section:_

Which section, where, and in which document?

- Lc 45 is “sort of” like 3:1
- Lc 60 is “sort of” like 4.5:1
- Lc 75 is “sort of” like 7:1

The purpose of these was/is only to answer people's question "how does APCA values compare to WCAG 2" and nothing more. 


This is described more in detail at the [Visual Contrast white=paper wiki.](https://www.w3.org/WAI/GL/task-forces/silver/wiki/Visual_Contrast_of_Text_Subgroup/APCA_model#WCAG_2.x_to_Silver.2FAPCA_Comparison_Table)

**Comment by xi** [comment]
The section is in the README: https://github.com/Myndex/SAPC-APCA/blob/51000c0a69ae9f66b81fbb6a256d6ca55fa824d4/documentation/README.md#accessible-perceptual-contrast-algorithm-in-a-nutshell

**Comment by Myndex** [comment]
Updated documentation readme for be in sync with other documentation, in particular regarding the comparison levels. Closing this issue as complete.
