### ISSUE TITLE
www.myndex.com has an expired cert

### ISSUE THREAD

**Issue by Seirdy** [Myndex/SAPC-APCA#91]
**Does this relate to a web app or tool (i.e. you're an end user) OR is this about code or code integration (you're a developer).**

This relates to the https://www.myindex.com website

**Describe the bug**

The website https://www.myndex.com, containing the APCA calculator web app, has an expired TLS certificate. The certificate expired on the 24th.

**To Reproduce**

Visit https://www.myndex.com/APCA/ in a modern browser, or run `curl https://www.myndex.com/APCA/`.

**Expected behavior**

The website loads.

This behavior is device- and OS-independent; it appears in any correct implementation of webpki.

**Comment by Myndex** [comment]
AH nuts!! The update script must have some issue... Thanks @Seirdy will correct it ASAP, thank you for letting me know!

**Comment by Myndex** [comment]
Well this problem is deeper than I thought... something with the LetsEncrypt cert chain is totally borked... UGH... suggestions welcome.

**Comment by Seirdy** [comment]
There's always the option of requesting a totally new cert instead of renewing an existing one, or switching CA providers entirely (ZeroSSL offers free certs through the ACME protocol, just like LE). You'll need to update your server configs to point the new certificate path, or replace the old certificate path.

**Comment by Myndex** [comment]
Well, that was a really annoying bug to chase down. Closed as corrected. Resolution is discussed at [LetsEncrypt.](https://community.letsencrypt.org/t/macos-elcapitan-recent-renew-now-all-sites-fail/185295)
