### ISSUE TITLE
APCA Contrast Calculator: SSL cert expired

### ISSUE THREAD

**Issue by b2m9** [Myndex/SAPC-APCA#99]
**Does this relate to a web app or tool (i.e. you're an end user) OR is this about code or code integration (you're a developer).**

Regarding deployed version of APCA Contrast Calculator.

**Describe the bug**
SSL cert for `www.myndex.com` expired on Sunday, June 25th 2023.

**To Reproduce**
Visit [https://www.myndex.com/APCA/](https://www.myndex.com/APCA/)

**Screenshots**

Cert details from Firefox:
<img width="844" alt="image" src="https://github.com/Myndex/SAPC-APCA/assets/8492232/0a8a2f43-29b7-4e1d-964c-5d5abda758d9">

**Comment by Myndex** [comment]
Ah nuts... thank you @b2m9  the update script must be borked or something...

**Comment by Myndex** [comment]
Well thats fixed... thank you @b3m9 your report is much appreciated.
